# Generated by Django 3.0.8 on 2020-11-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password_hash', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Postcode', models.CharField(max_length=100)),
                ('TTN', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeTestKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTN_code', models.CharField(max_length=10)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
